// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ImpersonationData = {
    body?: never;
    path: {
        memberKey: string;
    };
    query?: never;
    url: '/umbraco/backoffice/impersonation/v1/Impersonation/{memberKey}';
};

export type ImpersonationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ImpersonationResponses = {
    /**
     * OK
     */
    200: string;
};

export type ImpersonationResponse = ImpersonationResponses[keyof ImpersonationResponses];

export type StopImpersonationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/backoffice/impersonation/v1/StopImpersonation';
};

export type StopImpersonationErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type StopImpersonationResponses = {
    /**
     * No Content
     */
    204: string;
};

export type StopImpersonationResponse = StopImpersonationResponses[keyof StopImpersonationResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44312' | (string & {});
};