// This file is auto-generated by @hey-api/openapi-ts

export enum EventMessageTypeModel {
    DEFAULT = 'Default',
    INFO = 'Info',
    ERROR = 'Error',
    SUCCESS = 'Success',
    WARNING = 'Warning'
}

export type NotificationHeaderModel = {
    message: string;
    category: string;
    type: EventMessageTypeModel;
};

export type ImpersonateData = {
    body?: never;
    path: {
        memberKey: string;
    };
    query?: never;
    url: '/umbraco/backoffice/impersonation/v1/impersonate/{memberKey}';
};

export type ImpersonateErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type ImpersonateResponses = {
    /**
     * OK
     */
    200: string;
};

export type ImpersonateResponse = ImpersonateResponses[keyof ImpersonateResponses];

export type ClientOptions = {
    baseUrl: 'https://localhost:44312' | (string & {});
};